name: Upload SQL to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload SQL files to Azure Synapse
        run: |
         $workspaceName = "satya-synapse-demo"
         $scriptName = "just-uploaded.sql"
         $scriptFilePath = "C:\Users\Satyakumar_Surisetti\Desktop\sqlfiles\just-uploaded.sql"
         $sqlPoolName = "Built-in"
         $databaseName = "RAMS-demo"

         $credential = Get-Credential
         Connect-AzAccount -Credential $credential

         Set-AzSynapseSqlScript -WorkspaceName $workspaceName -ScriptName $scriptName -File $scriptFilePath -SqlPoolName $sqlPoolName -DatabaseName $databaseName

