name: Upload SQL to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload SQL files to Azure Synapse
        run: |
          $localFolderPath = "sqlfiles"
          $serverName = "satya-synapse-demo"
          $databaseName = "RAMS-demo"
          $username = "Admin"
          $password = "@Mna8888ES"
          
          $files = Get-ChildItem -Path $localFolderPath -Filter *.sql -File
          $connectionString = "Server=tcp:$serverName.database.windows.net,1433;Initial Catalog=$databaseName;Persist Security Info=False;User ID=$username;Password=$password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

          foreach ($file in $files) {
              $sqlScript = Get-Content $file.FullName | Out-String
              Invoke-SqlCmd -ConnectionString $connectionString -Query $sqlScript
          }
